site_name: "Async Task Pipeline"
site_description: "A framework for processing streaming data through CPU-intensive tasks"

theme:
  name: "material"
  features:
    - navigation.sections
    - navigation.tabs
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Examples: examples.md
  - API Reference:
    - Pipeline: api/pipeline.md
    - Stage: api/stage.md
    - Item: api/item.md
    - Utils: api/utils.md

plugins:
  - search
  - mermaid2
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            members_order: source
            merge_init_into_class: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
      # custom_fences:
      #   - name: mermaid
      #     class: mermaid
      #     format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
